name: Update Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight
  workflow_dispatch:     # allows manual triggering

jobs:
  update-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Contribution Graph Image
        run: |
          mkdir -p assets
          curl -o assets/contribution-graph.svg \
            "https://github-readme-activity-graph.vercel.app/graph?username=zihan07&theme=react-dark&area=true&custom_title=Yeastic%20Hassan's%20Code%20Activity"

      - name: Commit and Push if Graph Updated
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add assets/contribution-graph.svg
